frr version 8.5
frr defaults traditional
hostname core-router
log syslog informational
no ipv6 forwarding
!
interface eth1
!
interface eth2.10
!
interface eth2.20
!
interface eth2.30
!
interface eth2.40
!
interface eth2.50
!
router ospf
 network 10.0.0.0/30 area 0
 network 10.10.10.0/24 area 0
 network 10.10.20.0/24 area 0
 network 10.10.30.0/24 area 0
 network 10.10.40.0/24 area 0
 network 10.10.50.0/24 area 0
!
line vty
!
