frr version 8.5
frr defaults traditional
hostname edge-router
log syslog informational
no ipv6 forwarding
!
interface eth1
!
interface eth2
!
router ospf
 network 10.0.0.0/30 area 0
 network 10.10.99.0/24 area 0
!
line vty
!
