"use client";
import { useEffect, useState } from 'react';
import { FileText, HardDrive, Network, ScrollText, ShieldCheck } from 'lucide-react';
import { useIncidentStore } from '@/store/incidentStore';
import { useTopologyStore } from '@/store/topologyStore';
import { cn } from '@/utils/classnames';
import { authHeaders } from '@/lib/api';
const API = process.env.NEXT_PUBLIC_API_URL || '/api/v1';
type Tab = 'evidence'|'logs'|'files'|'devices';
export function EvidenceTabs({ className, incidentId }: { className?: string; incidentId?: string }) {
  const [tab,setTab]=useState<Tab>('evidence'); const { activeIncident }=useIncidentStore(); const nodes=useTopologyStore(s=>Array.from(s.nodes.values()));
  const [evidence,setEvidence]=useState<any[]>([]),[files,setFiles]=useState<any[]>([]),[logs,setLogs]=useState<any[]>([]);
  useEffect(()=>{let dead=false;if(!incidentId){setEvidence([]);setFiles([]);setLogs([]);return}const load=async()=>{try{const h=authHeaders();const [a,b,c]=await Promise.all([fetch(`${API}/forensics/incidents/${encodeURIComponent(incidentId)}/evidence`,{headers:h}),fetch(`${API}/forensics/incidents/${encodeURIComponent(incidentId)}/files`,{headers:h}),fetch(`${API}/forensics/incidents/${encodeURIComponent(incidentId)}/timeline`,{headers:h})]);const j=async(r:Response)=>r.ok?r.json():[];const [x,y,z]=await Promise.all([j(a),j(b),j(c)]);const list=(v:any,k='items')=>Array.isArray(v)?v:(Array.isArray(v?.[k])?v[k]:[]);if(!dead){setEvidence(list(x,'evidence'));setFiles(list(y));setLogs(list(z,'events'));}}catch{if(!dead){setEvidence(activeIncident?.evidence||[]);setLogs(activeIncident?.timeline_events||[]);}}};load();const id=window.setInterval(load,10000);return()=>{dead=true;window.clearInterval(id)}},[incidentId,activeIncident]);
  const tabs:[Tab,string,any][]=[['evidence','Evidence',ShieldCheck],['logs','Logs',ScrollText],['files','Files',FileText],['devices','Devices',Network]];
  return <div className={cn('h-full flex flex-col p-3 bg-[var(--bg-secondary)]',className)}><div className="flex gap-1 overflow-x-auto border-b border-[var(--border-primary)]">{tabs.map(([id,label,Icon])=><button key={id} onClick={()=>setTab(id)} className={cn('flex items-center gap-1.5 whitespace-nowrap px-2.5 py-1.5 text-xs font-medium rounded-t',tab===id?'text-[var(--accent-blue)] border-b-2 border-[var(--accent-blue)]':'text-[var(--text-muted)] hover:text-[var(--text-primary)]')}><Icon className="h-3.5 w-3.5"/>{label}</button>)}</div><div className="flex-1 min-h-0 overflow-auto pt-2">{tab==='evidence'&&<List empty={incidentId?'No evidence collected':'Select an incident to load evidence'} items={evidence} render={(e:any)=><><b>{e.name||e.evidence_type||'Evidence record'}</b><small>{e.sha256_hash||e.hash||e.description||'Integrity metadata unavailable'}</small></>}/>} {tab==='logs'&&<List empty="No timeline logs recorded" items={logs.slice(-40).reverse()} render={(e:any)=><><b className="capitalize">{String(e.kind||e.event_type||e.action||'telemetry').replace(/_/g,' ')}</b><small>{e.timestamp||e.created_at||e.message||e.description||`source: ${e.source||'telemetry'}`}</small></>}/>} {tab==='files'&&<List empty="No file events recorded" items={files} render={(e:any)=><><b>{e.file_path||e.path||e.name||'file event'}</b><small>{e.action||e.event_type||''}</small></>}/>} {tab==='devices'&&<List empty="No live devices discovered" items={nodes} render={(n:any)=><><b>{n.label||n.asset_id||n.id}</b><small>{n.zone||'unassigned'} · {n.status||'unknown'}</small></>}/>}</div></div>;
}
function List({items,empty,render}:{items:any[];empty:string;render:(x:any)=>any}){return items.length?<div className="space-y-1.5">{items.map((x,i)=><div key={x.id||x.event_id||i} className="rounded border border-[var(--border-primary)] bg-[var(--bg-tertiary)] px-2.5 py-2 text-xs"><div className="flex items-center gap-2"><span className="min-w-0 flex-1 truncate">{render(x).props.children[0]}</span></div><p className="mt-0.5 truncate text-[10px] text-[var(--text-secondary)]">{render(x).props.children[1]}</p></div>)}</div>:<div className="flex min-h-24 items-center justify-center text-center text-xs text-[var(--text-muted)]">{empty}</div>}
