"use client";

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { Activity, CheckCircle2, Server } from 'lucide-react';
import { demoRequest, getDemoSession } from '@/lib/demo-api';

export default function DevicePage() {
  const [state, setState] = useState<any>(null); const [error, setError] = useState('');
  useEffect(() => { let stopped = false; const refresh = async () => { try { const session = getDemoSession(); if (!session?.asset_id) throw new Error('Join session unavailable.'); const assetId = session.asset_id; await demoRequest('/heartbeat', { method: 'POST', body: JSON.stringify({ asset_id: assetId, hostname: session.hostname }) }); const next = await demoRequest<any>(`/asset/${encodeURIComponent(assetId)}/state`); if (!stopped) { setState(next); setError(''); } } catch (e: any) { if (!stopped) setError(e?.message || 'Connection unavailable.'); } }; refresh(); const timer = window.setInterval(refresh, 8000); return () => { stopped = true; clearInterval(timer); }; }, []);
  return <main className="grid min-h-[100dvh] place-items-center bg-[var(--bg-primary)] p-5 text-[var(--text-primary)]"><section className="w-full max-w-xl rounded-2xl border border-[var(--border-primary)] bg-[var(--bg-secondary)] p-6 shadow-2xl"><div className="mb-5 flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-[var(--accent-green)]/10 text-[var(--accent-green)]"><Server /></span><div><p className="text-xs uppercase tracking-wider text-[var(--text-secondary)]">Device enrollment</p><h1 className="text-xl font-semibold">{state?.hostname || 'Connecting device'}</h1></div></div>{error ? <p className="rounded-lg bg-[var(--accent-red)]/10 p-3 text-sm text-[var(--accent-red)]">{error}</p> : <div className="space-y-3 text-sm"><p className="flex items-center gap-2 text-[var(--accent-green)]"><CheckCircle2 className="h-4 w-4" /> Live heartbeat is active</p><dl className="grid grid-cols-2 gap-3 rounded-xl border border-[var(--border-primary)] p-4"><dt className="text-[var(--text-secondary)]">Role</dt><dd>{state?.role || '—'}</dd><dt className="text-[var(--text-secondary)]">LAN address</dt><dd className="font-mono">{state?.ip || 'Detecting…'}</dd><dt className="text-[var(--text-secondary)]">Status</dt><dd className="capitalize">{state?.status || 'online'}</dd></dl><p className="flex items-center gap-2 text-xs text-[var(--text-secondary)]"><Activity className="h-3.5 w-3.5 animate-pulse" /> Keep this tab open to remain visible in the topology.</p></div>}<Link href="/" className="mt-6 inline-flex rounded-lg bg-[var(--accent-blue)] px-4 py-2 text-sm font-medium text-white">Open command center</Link></section></main>;
}
